### ISSUE TITLE
[Feature] I wonder If it will support .spriteatlas.

### ISSUE THREAD

**Issue by CodeMasterYi** [Perfare/UnityStudio#716]
As the issue title.

**Comment by Perfare** [comment]
According to the suffix of the file, it is not possible to determine the specific file, you can upload it to me and I will view it.

**Comment by CodeMasterYi** [comment]
UI#CommonUI.spriteatlas
```YAML
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!687078895 &4343727234628468602
SpriteAtlas:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: UI#CommonUI
  m_EditorData:
    serializedVersion: 2
    textureSettings:
      serializedVersion: 2
      anisoLevel: 1
      compressionQuality: 50
      maxTextureSize: 2048
      textureCompression: 0
      filterMode: 1
      generateMipMaps: 0
      readable: 0
      crunchedCompression: 0
      sRGB: 1
    platformSettings:
    - serializedVersion: 2
      m_BuildTarget: Standalone
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 4
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 1
      m_AndroidETC2FallbackOverride: 0
    - serializedVersion: 2
      m_BuildTarget: iPhone
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 4
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 1
      m_AndroidETC2FallbackOverride: 0
    - serializedVersion: 2
      m_BuildTarget: Android
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 4
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 1
      m_AndroidETC2FallbackOverride: 0
    - serializedVersion: 2
      m_BuildTarget: DefaultTexturePlatform
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 4
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 0
      m_AndroidETC2FallbackOverride: 0
    packingSettings:
      serializedVersion: 2
      padding: 4
      blockOffset: 1
      allowAlphaSplitting: 0
      enableRotation: 0
      enableTightPacking: 0
    variantMultiplier: 1
    packables:
    - {fileID: 102900000, guid: 4b8d00eea363d47e7b41d8e5f0891a8c, type: 3}
    totalSpriteSurfaceArea: 34128
    bindAsDefault: 0
  m_MasterAtlas: {fileID: 0}
  m_PackedSprites:
  - {fileID: 21300000, guid: 94061b70cbf678c45a3df0540793abcf, type: 3}
  - {fileID: 21300000, guid: 355b0a417e2b9674383b00d6909162b9, type: 3}
  - {fileID: 21300000, guid: bc437ed6464751c4dbb5e0c8afb342e3, type: 3}
  m_PackedSpriteNamesToIndex:
  - bg_mask
  - btn_purple
  - btn_white
  m_Tag: UI#CommonUI
  m_IsVariant: 0
```

TA_CommonUI@1.0.spriteatlas
```YAML
%YAML 1.1
%TAG !u! tag:unity3d.com,2011:
--- !u!687078895 &4343727234628468602
SpriteAtlas:
  m_ObjectHideFlags: 0
  m_CorrespondingSourceObject: {fileID: 0}
  m_PrefabInstance: {fileID: 0}
  m_PrefabAsset: {fileID: 0}
  m_Name: TA_CommonUI@1.0
  m_EditorData:
    serializedVersion: 2
    textureSettings:
      serializedVersion: 2
      anisoLevel: 1
      compressionQuality: 50
      maxTextureSize: 2048
      textureCompression: 0
      filterMode: 1
      generateMipMaps: 0
      readable: 0
      crunchedCompression: 0
      sRGB: 1
    platformSettings:
    - serializedVersion: 2
      m_BuildTarget: Standalone
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 12
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 1
      m_AndroidETC2FallbackOverride: 0
    - serializedVersion: 2
      m_BuildTarget: iPhone
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 56
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 1
      m_AndroidETC2FallbackOverride: 0
    - serializedVersion: 2
      m_BuildTarget: Android
      m_MaxTextureSize: 2048
      m_ResizeAlgorithm: 0
      m_TextureFormat: 47
      m_TextureCompression: 1
      m_CompressionQuality: 50
      m_CrunchedCompression: 0
      m_AllowsAlphaSplitting: 0
      m_Overridden: 1
      m_AndroidETC2FallbackOverride: 0
    packingSettings:
      serializedVersion: 2
      padding: 4
      blockOffset: 1
      allowAlphaSplitting: 0
      enableRotation: 1
      enableTightPacking: 1
    variantMultiplier: 1
    packables:
    - {fileID: 102900000, guid: 4b8d00eea363d47e7b41d8e5f0891a8c, type: 3}
    totalSpriteSurfaceArea: 17228
    bindAsDefault: 0
  m_MasterAtlas: {fileID: 4343727234628468602, guid: 94df930167a814f9888ca77f46b424df,
    type: 2}
  m_PackedSprites:
  - {fileID: 21300000, guid: 94061b70cbf678c45a3df0540793abcf, type: 3}
  - {fileID: 21300000, guid: 355b0a417e2b9674383b00d6909162b9, type: 3}
  - {fileID: 21300000, guid: bc437ed6464751c4dbb5e0c8afb342e3, type: 3}
  m_PackedSpriteNamesToIndex:
  - bg_mask
  - btn_purple
  - btn_white
  m_Tag: UI#CommonUI
  m_IsVariant: 1
```
